# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: author/ferdinand-avikpe
    weight: 10
  - name: Research
    identifier: research
    weight: 20
  - name: Projects 
    parent: research
    url: project
    weight: 10
  - name: Publications 
    parent: research
    url: publication
    weight: 10
  - name: Teaching 
    url: teaching
    weight: 30 
  - name: Experience
    identifier: experience
    weight: 40
  - name: Leadership
    parent: experience
    url: leadership
    weight: 30
  - name: Volunteer
    parent: experience
    url: volunteer
    weight: 30
  - name: Contact
    url: contact
    weight: 50

